### ISSUE TITLE
AuthenticationManagerBean

### ISSUE THREAD

**Issue by Lelv** [szerhusenBC/jwt-spring-security-demo#18]
Hey, great job with this project - sadly for me I can't get it to work. I'm trying to implement it on a project for my college that's making us transition from the good old cookies to tokens, and I tried to do it as you but I'm getting an error that the authenticationManager can't be autowired on the authenticationrestcontroller - do you know why it could be? Thanks in advanced

**Comment by szerhusenBC** [comment]
This are too less informations for my to say anything. Can you post the stacktrace of the exception and the class you trying to autowire the AuthenticationManager?

**Comment by Lelv** [comment]
Thanks for the amazingly fast response. 

I was trying to use the Autowired AuthenticationManager on the AuthenticationController, but spring told me that it wasn't able to autowire it. I was able to fix it by adding the following to the WebSecurityConfig:

`    @Bean(name = BeanIds.AUTHENTICATION_MANAGER)
    public AuthenticationManager authenticationManagerBean() throws Exception {
        return super.authenticationManagerBean();
     }`

Maybe the problem is that I'm not using spring boot, but other spring dependencies (?). Anyways, that helped me, and was able to move forwards. I don't have it working yet though cuz I've encountered another problem but don't want to bother you with it since I haven't tried to fix it yet, and the following days I'll be working on something else, but I can keep you updated

**Comment by szerhusenBC** [comment]
It may be the problem that you're not using Spring Boot.

I made this demo to explicitly make a setup for SpringBoot because at that time I didn't find any proper setup that is running out if the box. But I found existing demos for "standard" Spring configurations. Perhaps you should google a little bit for that ...

Because this question isn't Spring Boot related I will close it now. If you found a solution for your problem you can of course tell it to me ;)
