### ISSUE TITLE
STATELESS is causing SecurityContextHolder.getContext().getAuthentication() always be null.

### ISSUE THREAD

**Issue by bfwg** [szerhusenBC/jwt-spring-security-demo#33]
`SecurityContextHolder.getContext().getAuthentication() == null` seems to be always null in https://github.com/szerhusenBC/jwt-spring-security-demo/blob/master/src/main/java/org/zerhusen/security/JwtAuthenticationTokenFilter.java#L42

**Comment by arkaprovo** [comment]
It is Until [this  ](https://github.com/szerhusenBC/jwt-spring-security-demo/blob/master/src/main/java/org/zerhusen/security/controller/AuthenticationRestController.java#L50)method successfully get executed. and it totally makes sense because you don't want unauthenticated users to grant access to your api.

**Comment by arkaprovo** [comment]
@bfwg & @szerhusenBC  I have a question, assuming doFilterInternal method is setting Authentication with every valid request **(by using `SecurityContextHolder.getContext().setAuthentication(authentication);`**) 
If there are multiple requests will there be a confliction? For example, if I am using the authentication for Authorization **(`@PreAuthorize("@validator.isAuthorised(true,#request,authentication)")`)** on rest end points to determine the access will it be safe?

**Comment by szerhusenBC** [comment]
@bfwg It is not always null, only in the case, that there is no authorization request header. The problem is, that the filter now filters **every** request and many times there is no authorization header. It would be better if the filter only filters requests that should be secured based on the security configuration.

**Comment by bfwg** [comment]
Hi @szerhusenBC , you are correct. This is how I did to filter base on response path: https://github.com/bfwg/springboot-jwt-starter/blob/master/src/main/java/com/bfwg/security/auth/TokenAuthenticationFilter.java#L50
I imagine there must be a more elegant way to handle this. Please let me know what you think.

**Comment by szerhusenBC** [comment]
@bfwg  While migrating to Spring Boot 2 I did some fixes and optimizations. It seems that the filter now only is invoked for the secured URLs. So I'm closing this ticket now.
