### ISSUE TITLE
How do you do anything? Just got project running.

### ISSUE THREAD

**Issue by SCuvanov** [szerhusenBC/jwt-spring-security-demo#61]
I get this project running, but going to localhost:8080 shows an alert for username and password. I enter the credentials provided but it literally does nothing except ask again for username and password.

Am I going about doing this wrong? This seems to be an issue with every project I have tried to get running. I get everything going and get hit with this wall.

**Comment by szerhusenBC** [comment]
I'm afraid I can't help you. I have no problems running and opening the start page of this project. If you really have this problem with EVERY web project you are running, the problem is somewhere in your setup. Maybe you are behind an Apache or nginx server that has an authentication active ...

Because this problem is not related to this project I#m closing this ticket now.
